# Generated by Django 4.2.6 on 2023-10-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
